.
SpongesBoob/Bloc1-Slam pull request #5
Opened 2023-10-12 14:47 UTC by SpongesBoob

2023-10-13 14:18 UTC, jcheron requested changes
Voir les commentaires dans le code

2023-10-13 14:18 UTC, jcheron commented on docs/pages/td4/calculatrice.html
> +    <button onclick="clearResult()">C</button>
C'est une mauvaise pratique que d'utiliser l'attribut `onclick` du HTML
il faut utiliser le addEventListener en JS à la place

2023-10-13 14:18 UTC, jcheron commented on docs/pages/td4/style-texte.html
> +        <input type="text" id="texte" oninput="updateText()" value="Hello, world!">
idem : mauvaise pratique
Associer les events avec des addEventListener

2023-10-14 08:32 UTC, SpongesBoob commented
TD4 modifié

2023-10-14 08:33 UTC, merged